const REPORT_API_BASE_URL = "http://localhost:8001";

function downloadHtmlFile(filename, html) {
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename || "academic_report.html";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

async function exportAcademicReport() {
    const studentNameInput = document.getElementById("studentName");
    const exportStatus = document.getElementById("exportStatus");
    const studentName = studentNameInput ? studentNameInput.value.trim() : "";

    if (!studentName) {
        alert("Please enter the student name before exporting a report.");
        return;
    }

    let gpaData = null;
    try {
        gpaData = JSON.parse(localStorage.getItem("academicGpaReport") || "null");
    } catch (error) {
        gpaData = null;
    }

    const schedule = window.lastStudySchedule || [];
    if (!gpaData && schedule.length === 0) {
        alert("Generate a study plan or calculate a GPA first, then export the report.");
        return;
    }

    if (exportStatus) {
        exportStatus.textContent = "Generating report...";
    }

    try {
        const response = await fetch(`${REPORT_API_BASE_URL}/report/generate`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                student_name: studentName,
                gpa: gpaData ? gpaData.gpa : null,
                courses: gpaData ? gpaData.courses : [],
                schedule: schedule,
                notes: "Combined academic summary generated by Academic AI Assistant.",
            }),
        });

        const data = await response.json();

        if (!response.ok || !data.success) {
            const message = data.detail || data.message || "Failed to generate report";
            if (exportStatus) {
                exportStatus.textContent = `Error: ${message}`;
            }
            return;
        }

        downloadHtmlFile(data.filename, data.html);
        window.open(`${REPORT_API_BASE_URL}${data.download_url}`, "_blank");

        if (exportStatus) {
            exportStatus.textContent = `Report saved as ${data.filename}`;
        }
    } catch (error) {
        if (exportStatus) {
            exportStatus.textContent = `Error: ${error.message}`;
        }
    }
}

document.addEventListener("DOMContentLoaded", function () {
    const exportButton = document.getElementById("exportReportButton");
    if (exportButton) {
        exportButton.addEventListener("click", exportAcademicReport);
    }
});
